package com.jw.controller;

import com.jw.model.PublicadoresModel;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Felipe Kraemer
 */
public class Main extends javax.swing.JFrame {

    String usuario = "";
    
    private String getUsuario() {
        return this.usuario;
    }
    
    private void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setMinimumSize(new java.awt.Dimension(Toolkit.getDefaultToolkit().getScreenSize()));
        setResizable(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuPrincipal = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadPublicadores = new javax.swing.JMenuItem();
        mnuCadProgramaEscola = new javax.swing.JMenuItem();
        mnuCadLicoes = new javax.swing.JMenuItem();
        mnuCadCenarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuProgramaSemanal = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();
        frmLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();
        btnOK = new javax.swing.JButton();
        mnuPrincipal1 = new javax.swing.JMenuBar();
        mnuCadastro1 = new javax.swing.JMenu();
        mnuCadApostila = new javax.swing.JMenuItem();
        mnuCadLicoes1 = new javax.swing.JMenuItem();
        mnuCadPublicadores1 = new javax.swing.JMenuItem();
        mnuDesignacoes = new javax.swing.JMenu();
        mnuProgramaSemanal1 = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuSobre1 = new javax.swing.JMenuItem();
        mnuOpcoes = new javax.swing.JMenu();
        mnuLogoff = new javax.swing.JMenuItem();
        mnuDesligar = new javax.swing.JMenuItem();

        mnuCadastro.setText("Cadastro");
        mnuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroActionPerformed(evt);
            }
        });

        mnuCadPublicadores.setText("Publicadores");
        mnuCadPublicadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadPublicadoresActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadPublicadores);

        mnuCadProgramaEscola.setText("Programa da Escola");
        mnuCadProgramaEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadProgramaEscolaActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadProgramaEscola);

        mnuCadLicoes.setText("Lições da Escola");
        mnuCadLicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadLicoesActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadLicoes);

        mnuCadCenarios.setText("Cenários");
        mnuCadCenarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadCenariosActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadCenarios);

        mnuPrincipal.add(mnuCadastro);

        jMenu1.setText("Visualizar");

        mnuProgramaSemanal.setText("Gerenciamento de Designações");
        mnuProgramaSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProgramaSemanalActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProgramaSemanal);

        mnuPrincipal.add(jMenu1);

        jMenu2.setText("Ajuda");

        mnuSobre.setText("Sobre");
        mnuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobreActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSobre);

        mnuPrincipal.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nossa Vida e Ministério Cristão");

        frmLogin.setTitle("Identifique-se");
        frmLogin.setVisible(true);

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmLoginLayout = new javax.swing.GroupLayout(frmLogin.getContentPane());
        frmLogin.getContentPane().setLayout(frmLoginLayout);
        frmLoginLayout.setHorizontalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addGap(67, 67, 67))
        );
        frmLoginLayout.setVerticalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuPrincipal1.setEnabled(false);

        mnuCadastro1.setText("Cadastro");
        mnuCadastro1.setEnabled(false);
        mnuCadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastro1ActionPerformed(evt);
            }
        });

        mnuCadApostila.setText("Apostila");
        mnuCadApostila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadApostilaActionPerformed(evt);
            }
        });
        mnuCadastro1.add(mnuCadApostila);

        mnuCadLicoes1.setText("Lições da Escola");
        mnuCadLicoes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadLicoes1ActionPerformed(evt);
            }
        });
        mnuCadastro1.add(mnuCadLicoes1);

        mnuCadPublicadores1.setText("Publicadores");
        mnuCadPublicadores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadPublicadores1ActionPerformed(evt);
            }
        });
        mnuCadastro1.add(mnuCadPublicadores1);

        mnuPrincipal1.add(mnuCadastro1);

        mnuDesignacoes.setText("Designações");
        mnuDesignacoes.setEnabled(false);

        mnuProgramaSemanal1.setText("Programa Semanal");
        mnuProgramaSemanal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProgramaSemanal1ActionPerformed(evt);
            }
        });
        mnuDesignacoes.add(mnuProgramaSemanal1);

        mnuPrincipal1.add(mnuDesignacoes);

        mnuAjuda.setText("Ajuda");
        mnuAjuda.setEnabled(false);

        mnuSobre1.setText("Sobre");
        mnuSobre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobre1ActionPerformed(evt);
            }
        });
        mnuAjuda.add(mnuSobre1);

        mnuPrincipal1.add(mnuAjuda);

        mnuOpcoes.setText("Opções");
        mnuOpcoes.setEnabled(false);

        mnuLogoff.setText("Sair");
        mnuLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoffActionPerformed(evt);
            }
        });
        mnuOpcoes.add(mnuLogoff);

        mnuDesligar.setText("Desligar");
        mnuDesligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesligarActionPerformed(evt);
            }
        });
        mnuOpcoes.add(mnuDesligar);

        mnuPrincipal1.add(mnuOpcoes);

        setJMenuBar(mnuPrincipal1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frmLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frmLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadPublicadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadPublicadoresActionPerformed
        new CadPublicadores().setVisible(true);
    }//GEN-LAST:event_mnuCadPublicadoresActionPerformed

    private void mnuCadProgramaEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadProgramaEscolaActionPerformed
        //new CadProgramaEscola().setVisible(true);
    }//GEN-LAST:event_mnuCadProgramaEscolaActionPerformed

    private void mnuCadLicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadLicoesActionPerformed
        //new CadLicoes().setVisible(true);
    }//GEN-LAST:event_mnuCadLicoesActionPerformed

    private void mnuCadCenariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadCenariosActionPerformed
        //new CadCenarios().setVisible(true);
    }//GEN-LAST:event_mnuCadCenariosActionPerformed

    private void mnuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroActionPerformed
        // TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_mnuCadastroActionPerformed

    private void mnuProgramaSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProgramaSemanalActionPerformed
        //new ProgramaSemanal().setVisible(true);
    }//GEN-LAST:event_mnuProgramaSemanalActionPerformed

    private void mnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreActionPerformed
        new Sobre().setVisible(true);
    }//GEN-LAST:event_mnuSobreActionPerformed

    private void mnuCadPublicadores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadPublicadores1ActionPerformed
        new CadPublicadores(getUsuario()).setVisible(true);
    }//GEN-LAST:event_mnuCadPublicadores1ActionPerformed

    private void mnuCadLicoes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadLicoes1ActionPerformed
        new CadLicoes().setVisible(true);
    }//GEN-LAST:event_mnuCadLicoes1ActionPerformed

    private void mnuCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastro1ActionPerformed
        // TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_mnuCadastro1ActionPerformed

    private void mnuProgramaSemanal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProgramaSemanal1ActionPerformed
        new ProgramaSemanal().setVisible(true);
    }//GEN-LAST:event_mnuProgramaSemanal1ActionPerformed

    private void mnuSobre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobre1ActionPerformed
        new Sobre().setVisible(true);
    }//GEN-LAST:event_mnuSobre1ActionPerformed

    private void mnuCadApostilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadApostilaActionPerformed
        new CadApostila().setVisible(true);
    }//GEN-LAST:event_mnuCadApostilaActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        boolean pesquisar = true;
        String usuario = "";
        String senha = "";
        if (txtUsuario.getPassword() == null || new String(txtUsuario.getPassword()).equals("")) {
            pesquisar = false;
        } else {
            usuario = new String(txtUsuario.getPassword());
        }
        if (txtSenha.getPassword() == null || new String(txtSenha.getPassword()).equals("")) {
            pesquisar = false;
        } else {
            senha = new String(txtSenha.getPassword());
        }
        
        if (pesquisar) {
            String nome = PublicadoresModel.pesquisarUsuario(usuario, senha);
            
            if (!nome.equals("")) {
                frmLogin.dispose();
                mnuCadastro1.setEnabled(true);
                mnuDesignacoes.setEnabled(true);
                mnuAjuda.setEnabled(true);
                mnuOpcoes.setEnabled(true);

                this.setTitle(this.getTitle() + "            USUÁRIO: " + nome);
                JOptionPane.showMessageDialog(this, "Bem-vindo, " + nome + "!");
                
                setUsuario(nome);
            } else {
                txtUsuario.setText("");
                txtSenha.setText("");
                txtUsuario.requestFocus();
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Usuário e senha são obrigatórios.");
        }
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void mnuDesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesligarActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Deseja realmente desligar o programa?", "Atenção", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ret == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuDesligarActionPerformed

    private void mnuLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoffActionPerformed
        int ret = JOptionPane.showConfirmDialog(this, "Deseja realmente sair do programa?", "Atenção", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ret == 0) {
            this.setTitle("Nossa Vida e Ministério Cristão");
            txtUsuario.setText("");
            txtSenha.setText("");
            mnuCadastro1.setEnabled(false);
            mnuDesignacoes.setEnabled(false);
            mnuAjuda.setEnabled(false);
            mnuOpcoes.setEnabled(false);
            frmLogin.setVisible(true);
        }
    }//GEN-LAST:event_mnuLogoffActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        btnOKActionPerformed(evt);
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        btnOKActionPerformed(evt);
        txtUsuario.requestFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JInternalFrame frmLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuItem mnuCadApostila;
    private javax.swing.JMenuItem mnuCadCenarios;
    private javax.swing.JMenuItem mnuCadLicoes;
    private javax.swing.JMenuItem mnuCadLicoes1;
    private javax.swing.JMenuItem mnuCadProgramaEscola;
    private javax.swing.JMenuItem mnuCadPublicadores;
    private javax.swing.JMenuItem mnuCadPublicadores1;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenu mnuCadastro1;
    private javax.swing.JMenu mnuDesignacoes;
    private javax.swing.JMenuItem mnuDesligar;
    private javax.swing.JMenuItem mnuLogoff;
    private javax.swing.JMenu mnuOpcoes;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenuBar mnuPrincipal1;
    private javax.swing.JMenuItem mnuProgramaSemanal;
    private javax.swing.JMenuItem mnuProgramaSemanal1;
    private javax.swing.JMenuItem mnuSobre;
    private javax.swing.JMenuItem mnuSobre1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
